### ISSUE TITLE
Several globalnames

### ISSUE THREAD

**Issue by swb-ops** [polaris-gslb/polaris-core#64]
Hi guys,
I have a configuration of polaris for one domain and it works really well. 
I am currently trying to add a second domain in my config, but it doesn't work.
My polaris-lb.yaml:
```
pools:
    gslb:
        monitor: http
        monitor_params:
            use_ssl: true
            port: 443
            hostname: domain1.com
        lb_method: wrr 
        fallback: any
        members:
        - ip: 10.0.0.1
          name: dc1
          weight: 1
        - ip: 10.1.0.1
          name: dc2
          weight: 1

pools:
    gslb2:
        monitor: http
        monitor_params:
            use_ssl: true
            port: 443
            hostname: domain2.com
        lb_method: wrr 
        fallback: any
        members:
        - ip: 192.168.0.1
          name: dc1
          weight: 1
        - ip: 192.168.1.1
          name: dc2
          weight: 1

globalnames:
    domain1.com:
        pool: gslb
        ttl: 1

globalnames:
    domain2.com:
        pool: gslb2
        ttl: 1
```

Please tell me how to add a second domain.

**Comment by Aaron-loadbalancer-org** [comment]
try this:

```
pools:
    gslb:
        monitor: http
        monitor_params:
            use_ssl: true
            port: 443
            hostname: domain1.com
        lb_method: wrr 
        fallback: any
        members:
        - ip: 10.0.0.1
          name: dc1
          weight: 1
        - ip: 10.1.0.1
          name: dc2
          weight: 1
    gslb2:
        monitor: http
        monitor_params:
            use_ssl: true
            port: 443
            hostname: domain2.com
        lb_method: wrr 
        fallback: any
        members:
        - ip: 192.168.0.1
          name: dc1
          weight: 1
        - ip: 192.168.1.1
          name: dc2
          weight: 1

globalnames:
    domain1.com:
        pool: gslb
        ttl: 1
    domain2.com:
        pool: gslb2
        ttl: 1
```
